#!/bin/bash
# download RecCascResults.root from all processed runs from the Valparaiso
# arguments: year(16,17,18,19), cluster(from zero/0)

rsync -r -u --include="*/" --include="recCascResults.root" --include="singleRecCasc_*.root" --include="*.json" --exclude="*" VM240:/home/fajtak/data/exp20$1/cluster$2/ $CEPH_MNT/dataVM240/exp$1/cluster$2/ --progress