#!/bin/bash
# download RecCascResults.root from all processed runs from the Valparaiso
# arguments: year(16,17,18,19), cluster(from zero/0)

rsync -r -u --include="*/" --include="recCascResults.root" --include="singleRecCasc_*.root" --exclude="*" val:/media/bajkal/exp$1_barsv051/cluster$2/ /Data/BaikalData/dataVal/exp$1/cluster$2/ --progress