#!/bin/bash
# downloads joint.event.root file for given cluster, year and runID
# arguments: year(16,17,18,19), cluster(from zero/0), runID (from 1/one)

command=$(printf "%04d" $3)

# rsync -r -u --include="*/" --include="recCascResults.root" --include="singleRecCasc_*.root" --exclude="*" val:/media/bajkal/exp$1_barsv051/cluster$2/ /Data/BaikalData/dataVal/exp$1/cluster$2/ --progress

rsync -u val:/media/bajkal/exp$1_barsv051/cluster$2/${command}/*joint.events.root $CEPH_MNT/exp$1_barsv051/cluster$2/${command}/ --progress
rsync -u val:/media/bajkal/exp$1_barsv051/cluster$2/${command}/*.qcalib $CEPH_MNT/exp$1_barsv051/cluster$2/${command}/ --progress

