#!/bin/bash
# join per-run generated program output logs to a single per-season and per-cluster file
# arguments: year(16,17,18,19), cluster(from zero/0), path to log files

if [ "$#" -eq 3 ]; then
	cd $3
	rm programOutput_$1_$2.log
else
	cd ../../logs
	rm programOutput_$1_$2.log
fi

for runID in {1..999}
do
	if test -f "programOutput_$1_$2_$runID.log"; then
		cat programOutput_$1_$2_$runID.log >> programOutput_$1_$2.log
	fi
done