#!/bin/bash
# process all joint.event.root files for given year and cluster
# arguments: year(16,17,18,19), cluster(from zero/0), optional parameter nCores used for processing

[ -z $1 ] && echo "Season info missing" && exit
[ -z $2 ] && echo "Cluster info missing" && exit

rm ../logs/programOutput_$1_$2_*.log

if [ "$1" -eq "16" ];
	then
		parallel "(time ./new-reconstruct-cascade -s 20$1 -c $2 -r {1} -o /home/fajtak/data) 2>&1 | tee ../logs/programOutput_$1_$2_{1}.log" ::: {1..999}
	else
		parallel "(time ./new-reconstruct-cascade -s 20$1 -c $2 -r {1} -t r01_i01_j01_t01 -o /home/fajtak/data/) 2>&1 | tee ../logs/programOutput_$1_$2_{1}.log" ::: {1..100}
fi
