#!/bin/bash
# process all joint.event.root files for given year and cluster
# arguments: year(16,17,18,19), cluster(from zero/0), start runID

[ -z $1 ] && echo "Season info missing" && exit
[ -z $2 ] && echo "Cluster info missing" && exit

# rm ../logs/programOutput_$1_$2_*.log
# rm ../logs/processingTime_$1_$2.log

processFiles=()

for runID in {1..9}
do
	command=$(printf "%04d" $runID)
	if [ -d "/home/fajtak/data/exp20$1/cluster$2/${command}/" ]; then
		if [ ! -f "/home/fajtak/data/exp20$1/cluster$2/${command}/recCascResults.root" ]; then
			processFiles+=( $runID )
		fi
	fi
done

echo "Runs to be processed:"
echo ${processFiles[@]}

date >> ../logs/processingTime_$1_$2.log
printf '%s\n' "${processFiles[@]}" | parallel -I% --max-args 1 "(time ./new-reconstruct-cascade -s 20$1 -c $2 -r % -o /home/fajtak/data -w -q -g -l -x ../configs/s$1_c$2.rc) 2>&1 | tee ../logs/programOutput_$1_$2_%.log"
date >> ../logs/processingTime_$1_$2.log
