#!/bin/bash
# process all joint.event.root files for given year and cluster
# arguments: year(16,17,18,19), cluster(from zero/0), temp folder

[ -z $1 ] && echo "Season info missing" && exit
[ -z $2 ] && echo "Cluster info missing" && exit
[ -z $3 ] && echo "Tmp folder path missing" && exit

rm ../logs/programOutput_$1_$2_*.log
rm ../logs/processingTime_$1_$2.log

date >> ../logs/processingTime_$1_$2.log

	parallel ../scripts/bash/processLocalRun $1 $2 {1} $3 ::: {1..999}

date >> ../logs/processingTime_$1_$2.log
