#!/bin/bash
# process all new joint.event.root files for given year and cluster
# by new it is meant a runs where joint.event.root file is present but no recCascResults.root is found in the given folder
# arguments: year(16,17,18,19), cluster(from zero/0)

for runID in {1..999}
do
	command=$(printf "%04d" $runID)
	if [ -d "/media/bajkal/exp16_barsv051/cluster$2/${command}/" ]; then
		if [ ! -f "/media/bajkal/exp16_barsv051/cluster$2/${command}/recCascResults.root" ]; then
			./new-reconstruct-cascade -s 20$1 -c $2 -r $runID -o "remote" -x ../src/config.rc
		fi
	fi
done