#!/bin/bash
# process all joint.event.root files for given year and cluster
# arguments: year(16,17,18,19), cluster(from zero/0), optional parameter nCores used for processing

nCores=1
count=0

[ -z $1 ] && echo "Season info missing" && exit
[ -z $2 ] && echo "Cluster info missing" && exit
[ ! -z $3 ] && nCores=$3

rm ../logs/programOutput_$1_$2_*.log

for runID in {1..999}
do
	if [ "$1" -eq "16" ];
	then
		( time ./new-reconstruct-cascade -s 20$1 -c $2 -r $runID -o /home/fajtak/data) 2>&1 | tee ../logs/programOutput_$1_$2_$runID.log &
	else
		( time ./new-reconstruct-cascade -s 20$1 -c $2 -r $runID -t r01_i01_j01_t01 -o /home/fajtak/data/) 2>&1 | tee ../logs/programOutput_$1_$2_$runID.log &
	fi
	(( count ++ ))
	if (( count == nCores )); then
			wait
		count=0
	fi
done
