#!/bin/bash
# process all joint.event.root files for given year and cluster
# arguments: year(16,17,18,19), cluster(from zero/0)

for runID in {1..999}
do
	if [ "$1" -eq "16" ];
	then
		time ./new-reconstruct-cascade -s 20$1 -c $2 -r $runID -o /home/fajtak/data/
	else
		time ./new-reconstruct-cascade -s 20$1 -c $2 -r $runID -t r01_i01_j01_t01 -o /home/fajtak/data/
	fi
done
