#!/bin/bash
# process all joint.event.root files for given year and cluster
# arguments: year(16,17,18,19), cluster(from zero/0), optional parameter nCores used for processing

nCores=1
count=0

[ -z $1 ] && echo "Season info missing" && exit
[ -z $2 ] && echo "Cluster info missing" && exit
[ ! -z $3 ] && nCores=$3

rm ../logs/programOutput_$1_$2_*.log

for runID in {1..999}
do
	( time ./new-reconstruct-cascade -s 20$1 -c $2 -r $runID ) 2>&1 | tee ../logs/programOutput_$1_$2_$runID.log &
	(( count ++ ))
	if (( count == nCores )); then
			wait
		count=0
	fi
done
