#!/bin/bash
# download a run from eos a process it
# arguments: year(16,17,18,19), cluster(from zero/0), run(from one/1)

[ -z $1 ] && echo "Season info missing" && exit
[ -z $2 ] && echo "Cluster info missing" && exit
[ -z $3 ] && echo "Run info missing" && exit

fullRunID=$(printf "%04d" $3)
copyClusterID=$(printf "%d" $runID+1)

echo $fullRunID
echo $copyClusterID

# echo "$CLUSTERS" | parallel $BASE/process-cluster.sh --season $SEASON --cluster {} --dir "$PRODUCTION"
# echo "$RUNS" | parallel (time ./new-reconstruct-cascade -s 20$1 -c $2 -r {} ) 2>&1 | tee ../logs/programOutput_$1_$2_{}.log

mkdir /home/fajtak/tmp/s$1_c$2_r$3/
eos cp /eos/baikalgvd/processed/20$1/cluster$copyClusterID/exp/dqm/v1.3/$fullRunID/*.qcalib /home/fajtak/tmp/s$1_c$2_r$3/
eos cp /eos/baikalgvd/processed/20$1/cluster$copyClusterID/exp/section/v1.3/$fullRunID/*.section.mask.root /home/fajtak/tmp/s$1_c$2_r$3/
eos cp /eos/baikalgvd/processed/20$1/cluster$copyClusterID/exp/joint/v1.3/$fullRunID/*.joint.events.marked.root /home/fajtak/tmp/s$1_c$2_r$3/

(time ./new-reconstruct-cascade -s 20$1 -c $2 -r $3 -i /home/fajtak/tmp/s$1_c$2_r$3/ -o /home/fajtak/data/ -q -g -l -x ../configs/s$1_c$2.rc) 2>&1 | tee ../logs/programOutput_$1_$2_$3.log

rm -rf /home/fajtak/tmp/s$1_c$2_r$3/