#!/bin/bash
# process all joint.event.root files for given year and cluster
# arguments: year(16,17,18,19), cluster(from zero/0)

for runID in {1..999}
do
	command=$(printf "%04d" $runID)
	if [ -d "/Data/BaikalData/exp16_barsv051/cluster$2/${command}/" ]; then
		if [ ! -f "/Data/BaikalData/exp16_barsv051/cluster$2/${command}/recCascResults.root" ]; then
			./new-reconstruct-cascade -s 20$1 -c $2 -r $runID
		fi
	fi
done