#!/bin/bash
# downloads all joint.event.root files for given year and cluster
# arguments: year(16,17,18,19), cluster(from zero/0)

for runID in {1001..1500}
do
	command=$(printf "%04d" $runID)
	echo $command

	if test -f "/eos/baikalgvd/mc_2016/nuatm/nuatm_feb19/wout/n_nuatm_gs_n2m_cl2016_x${command}.dat.gz.wout"; then
		if [ ! -f "/mnt/cephfs/user/fajtak/data/mc/nuatm_feb19/n_nuatm_gs_n2m_cl2016_x${command}.root" ]; then
			../../../../build/bin/bexport-mc -b --in /eos/baikalgvd/mc_2016/nuatm/nuatm_feb19/wout/n_nuatm_gs_n2m_cl2016_x${command}.dat.gz.wout --out /mnt/cephfs/user/fajtak/data/mc/nuatm_feb19/n_nuatm_gs_n2m_cl2016_x${command}.root
		fi
	fi
done